language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN>
    - secure: "kPXn0rZVuhtPzIfk7uYGm4m5gn5cMgF2fpWJJWum58JbtRPb+NOiSdQO/kEI+oDSTzUdz/yJj4FRpgRr2ouRKatceufCWqKAec5ihKtjrodPzf/uMoggRTGEOmGVtFnIjVf4UmWaMOHwcmxgWdeNjfHbO/N17oEcOUEzitSgKm6g0COzJJ1eXV0idigyrpPDBWuJIw5M4V0xHcT+VSoV+w/CR+gsIqREgk81CCZE2fpkt9BrmpfC2mRq8P1JR6HYF+2ym6UxqKFY4pnBuIBT18rmBYbeBT6j6VsnfvosJIoa39iCgdMTFjmpVht0/n3/ltQGJySAKGd616FgLKGgUzYdmMKOq+p+9tkcvU1/sjkacqbCDrQE4D7vTfgs4uxE/ZgUdA1YglBjtDIDBwfyjTZddTRCvefu68IkC5Ek+g2PPaxJ1zeb9wQCxVPqWpwbDcOAQlVZMfpckwSNZb6xt2+Lz9CtArqQT15bpXAvR7wKre6S+i05HzhUqE3v9qhVDcT8ZT9F8PzrJ+LEh6qycbg5rC0fDRVY7E3H+Dx/CttrpE16LBZ8Ros9o7jmG1PlR0dHv2huwx+S6M/xzPWi8/hc7CkFMHVv2q3+dpGQZ7Mfu0beG8aK58js/Fkk52J9E5k3CvXuWMZxK4OMd02Yz1TXbT5BhJBFuz91eg/ETOo="
  matrix:
    # doubleface account
    # to generate yours : travis encrypt KONNECTOR_CONFIG=\'"`cat konnector-dev-config.json | tr -d '\n'`"\' -r konnectors/cozy-konnector-bouyguesbox
    - secure: "WZhxfwUJ875CaJhU1ZYXw6KN3tdPwHHIAJaqnVnNicdMvzxRwPgRaYKSKxCEc2yLjnLwTITOEg2q2Y3iqxxpTmnJEmzF71YnEaHCO/f+za2XTE6dMSFUVkK/CfW+JlncKWgj+OD3I470Z4AjkwzwsMS2ClBKtwvlEByySbjoS/+IAiDRXdnLXZf4crh9bh8zFamiCc5W9fNllSr1UJ37YJ7fenuOWoQKj+rcjqwEYmCne1DBqCzv+5vAHS/bBuK5pxsDalLKoW7/+GhrUOWWMXwYU0LzJdLX2Qvtqvqmbogu5/tObqLfslA4jTH2hSA1DLVFFbjchwlwBfhGN1fGAQwwd+Wj9Z2xgBKXMYtVJajdgXXfE+hd4Y7KnQJlegjP42aSX+yLmFMLurt8+NieoBVzXUaJCj8CFcKZI1yVgPIOFXnaMjVXEkqkuIYHsh878UIkksfLo81MQ4HMp+vrKY0i8q0cRa2t3+dfEFO4xNwjzYwtuAV/Ah+b1sOj649+lUB138JCfGQ+eCr6VBRZ3r2cmLVpKLWXv2CZUkS6pJXRSM+qZ6O/ijCoiXMI2jq5wKIQ7gwOOSKA/tFZ3r9SUJS5SURmhY/ApcUAPuNgBd/4nuw3zk0QLHDA0Rybrsyag6+qJ6WY2HnFPlfHKfK3dp9F9S5LIj+Wn7/Gn3024jQ="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn lint
  - if [ $TRAVIS_SECURE_ENV_VARS = "true" ]; then yarn test; fi
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-bouyguesbox
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-bouyguesbox
    skip-cleanup: true
    script: yarn deploy:prod
    on:
      branch: prod
